cc -fsanitize=address -L/usr/local/opt/openblas/lib -L/usr/local/opt/llvm/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib  -L/usr/local/opt/openblas/lib -L/usr/local/opt/llvm/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib    -Wl,-stack_size,1000000  -framework CoreFoundation -o python Programs/python.o -L. -lpython3.6dm -lintl -ldl  -framework CoreFoundation     
cc -fsanitize=address -L/usr/local/opt/openblas/lib -L/usr/local/opt/llvm/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib  -L/usr/local/opt/openblas/lib -L/usr/local/opt/llvm/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl@1.1/lib    -Wl,-stack_size,1000000  -framework CoreFoundation -o Programs/_testembed Programs/_testembed.o -L. -lpython3.6dm -lintl -ldl  -framework CoreFoundation     
DYLD_LIBRARY_PATH=/Users/dojo/Library/Caches/Homebrew/Python-3.6.2 ./python -E -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
echo "generate-posix-vars failed" ; \
rm -f ./pybuilddir.txt ; \
exit 1 ; \
fi
=================================================================
==47907==ERROR: AddressSanitizer: odr-violation (0x0001058f4a00):
  [1] size=1 '<string literal>' Objects/bytearrayobject.c:410:50
  [2] size=1 '<string literal>' Objects/accu.c:11:39
These globals were registered at these points:
  [1]:
    #0 0x105f62637 in __asan_register_globals (libclang_rt.asan_osx_dynamic.dylib:x86_64+0xf637)
    #1 0x105fa4189 in __asan::AsanApplyToGlobals(void (*)(__asan_global*, unsigned long), void const*) (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x51189)
    #2 0x105f6256d in __asan_register_image_globals (libclang_rt.asan_osx_dynamic.dylib:x86_64+0xf56d)
    #3 0x1052e7c66 in asan.module_ctor (libpython3.6dm.dylib:x86_64+0xc66)
    #4 0x11223ac1d  (<unknown module>)
    #5 0x1122364a9  (<unknown module>)
    #6 0x112236440  (<unknown module>)
    #7 0x112235523  (<unknown module>)
    #8 0x1122355b8  (<unknown module>)
    #9 0x112227479  (<unknown module>)
    #10 0x11222b8c5  (<unknown module>)
    #11 0x112226248  (<unknown module>)
    #12 0x112226035  (<unknown module>)

  [2]:
    #0 0x105f62637 in __asan_register_globals (libclang_rt.asan_osx_dynamic.dylib:x86_64+0xf637)
    #1 0x105fa4189 in __asan::AsanApplyToGlobals(void (*)(__asan_global*, unsigned long), void const*) (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x51189)
    #2 0x105f6256d in __asan_register_image_globals (libclang_rt.asan_osx_dynamic.dylib:x86_64+0xf56d)
    #3 0x1052e7c66 in asan.module_ctor (libpython3.6dm.dylib:x86_64+0xc66)
    #4 0x11223ac1d  (<unknown module>)
    #5 0x1122364a9  (<unknown module>)
    #6 0x112236440  (<unknown module>)
    #7 0x112235523  (<unknown module>)
    #8 0x1122355b8  (<unknown module>)
    #9 0x112227479  (<unknown module>)
    #10 0x11222b8c5  (<unknown module>)
    #11 0x112226248  (<unknown module>)
    #12 0x112226035  (<unknown module>)

==47907==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: global '<string literal>' at Objects/bytearrayobject.c:410:50
==47907==ABORTING
/bin/sh: line 5: 47907 Abort trap: 6           DYLD_LIBRARY_PATH=/Users/dojo/Library/Caches/Homebrew/Python-3.6.2 ./python -E -S -m sysconfig --generate-posix-vars
generate-posix-vars failed
gmake[2]: *** [Makefile:565: pybuilddir.txt] Error 1
gmake[2]: Leaving directory '/Users/dojo/Library/Caches/Homebrew/Python-3.6.2'
gmake[1]: *** [Makefile:479: build_all_generate_profile] Error 2
gmake[1]: Leaving directory '/Users/dojo/Library/Caches/Homebrew/Python-3.6.2'
gmake: *** [Makefile:464: profile-opt] Error 2


### Above issue fixed after modified Objects/bytearrayobject.c ### 

const char *__asan_default_options() {
  return "verbosity=0:detect_odr_violation=0";
}

#### 
*** WARNING: renaming "_sqlite3" since importing it failed: dlopen(build/lib.macosx-10.12.6-x86_64-3.6-pydebug/_sqlite3.cpython-36dm-darwin.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /Users/dojo/Library/Caches/Homebrew/Python-3.6.2/build/lib.macosx-10.12.6-x86_64-3.6-pydebug/_sqlite3.cpython-36dm-darwin.so
  Expected in: flat namespace
 in /Users/dojo/Library/Caches/Homebrew/Python-3.6.2/build/lib.macosx-10.12.6-x86_64-3.6-pydebug/_sqlite3.cpython-36dm-darwin.so
==48878==T5: stack [0x700007988000,0x700007a08000) size 0x80000; local=0x700007a07320

Python build finished successfully!
The necessary bits to build these optional modules were not found:
ossaudiodev           spwd                                     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
atexit                pwd                   time               

Failed to build these modules:
_decimal                                                       


Following modules built successfully but were removed because they could not be imported:
_sqlite3                                                       


TEST failures
-------------------------------------------------------------------
0:00:11 load avg: 3.23 [  8/405] test_doctest
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2743, in test.test_doctest.test_CLI
Failed example:
    rc1, out1, err1
Expected:
    (0, b'', b'')
Got:
    (0, b'', b'==49377==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49377==Installed the sigaction for signal 11\n==49377==Installed the sigaction for signal 10\n==49377==T0: stack [0x7fff54fb9000,0x7fff55fb9000) size 0x1000000; local=0x7fff55fb40f0\n==49377==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2748, in test.test_doctest.test_CLI
Failed example:
    rc2, err2
Expected:
    (0, b'')
Got:
    (0, b'==49379==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49379==Installed the sigaction for signal 11\n==49379==Installed the sigaction for signal 10\n==49379==T0: stack [0x7fff5cdeb000,0x7fff5ddeb000) size 0x1000000; local=0x7fff5dde60e0\n==49379==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2817, in test.test_doctest.test_CLI
Failed example:
    rc1, err1
Expected:
    (1, b'')
Got:
    (1, b'==49381==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49381==Installed the sigaction for signal 11\n==49381==Installed the sigaction for signal 10\n==49381==T0: stack [0x7fff5c1f5000,0x7fff5d1f5000) size 0x1000000; local=0x7fff5d1f00a0\n==49381==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2845, in test.test_doctest.test_CLI
Failed example:
    rc2, out2, err2
Expected:
    (0, b'', b'')
Got:
    (0, b'', b'==49383==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49383==Installed the sigaction for signal 11\n==49383==Installed the sigaction for signal 10\n==49383==T0: stack [0x7fff5c248000,0x7fff5d248000) size 0x1000000; local=0x7fff5d2430d0\n==49383==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2847, in test.test_doctest.test_CLI
Failed example:
    rc3, out3, err3
Expected:
    (0, b'', b'')
Got:
    (0, b'', b'==49385==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49385==Installed the sigaction for signal 11\n==49385==Installed the sigaction for signal 10\n==49385==T0: stack [0x7fff54343000,0x7fff55343000) size 0x1000000; local=0x7fff5533e050\n==49385==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2852, in test.test_doctest.test_CLI
Failed example:
    rc4, err4
Expected:
    (1, b'')
Got:
    (1, b'==49387==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49387==Installed the sigaction for signal 11\n==49387==Installed the sigaction for signal 10\n==49387==T0: stack [0x7fff577d6000,0x7fff587d6000) size 0x1000000; local=0x7fff587d1090\n==49387==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2871, in test.test_doctest.test_CLI
Failed example:
    rc5, err5
Expected:
    (0, b'')
Got:
    (0, b'==49389==AddressSanitizer: libc interceptors initialized\n|| `[0x200000000000, 0x7fffffffffff]` || HighMem    ||\n|| `[0x140000000000, 0x1fffffffffff]` || HighShadow ||\n|| `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||\n|| `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||\n|| `[0x000000000000, 0x0fffffffffff]` || LowMem     ||\nMemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff\nredzone=16\nmax_redzone=2048\nquarantine_size_mb=256M\nmalloc_context_size=30\nSHADOW_SCALE: 3\nSHADOW_GRANULARITY: 8\nSHADOW_OFFSET: 0x100000000000\n==49389==Installed the sigaction for signal 11\n==49389==Installed the sigaction for signal 10\n==49389==T0: stack [0x7fff5773c000,0x7fff5873c000) size 0x1000000; local=0x7fff58737050\n==49389==AddressSanitizer Init done')
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2920, in test.test_doctest.test_CLI
Failed example:
    print(normalize(err))                    # doctest: +ELLIPSIS
Expected:
    Traceback (most recent call last):
      ...
    FileNotFoundError: [Errno ...] No such file or directory: 'nosuchfile'
Got:
    ==49391==AddressSanitizer: libc interceptors initialized
    || `[0x200000000000, 0x7fffffffffff]` || HighMem    ||
    || `[0x140000000000, 0x1fffffffffff]` || HighShadow ||
    || `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||
    || `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||
    || `[0x000000000000, 0x0fffffffffff]` || LowMem     ||
    MemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff
    redzone=16
    max_redzone=2048
    quarantine_size_mb=256M
    malloc_context_size=30
    SHADOW_SCALE: 3
    SHADOW_GRANULARITY: 8
    SHADOW_OFFSET: 0x100000000000
    ==49391==Installed the sigaction for signal 11
    ==49391==Installed the sigaction for signal 10
    ==49391==T0: stack [0x7fff5c6ac000,0x7fff5d6ac000) size 0x1000000; local=0x7fff5d6a7130
    ==49391==AddressSanitizer Init done
    Traceback (most recent call last):
      File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/runpy.py", line 193, in _run_module_as_main
        "__main__", mod_spec)
      File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/doctest.py", line 2787, in <module>
        sys.exit(_test())
      File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/doctest.py", line 2780, in _test
        verbose=verbose, optionflags=options)
      File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/doctest.py", line 2051, in testfile
        encoding or "utf-8")
      File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/doctest.py", line 226, in _load_testfile
        with open(filename, encoding=encoding) as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'nosuchfile'
**********************************************************************
File "/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_doctest.py", line 2931, in test.test_doctest.test_CLI
Failed example:
    print(normalize(err))                    # doctest: +ELLIPSIS
Expected:
    usage...invalid...nosuchoption...
Got:
    ==49393==AddressSanitizer: libc interceptors initialized
    || `[0x200000000000, 0x7fffffffffff]` || HighMem    ||
    || `[0x140000000000, 0x1fffffffffff]` || HighShadow ||
    || `[0x120000000000, 0x13ffffffffff]` || ShadowGap  ||
    || `[0x100000000000, 0x11ffffffffff]` || LowShadow  ||
    || `[0x000000000000, 0x0fffffffffff]` || LowMem     ||
    MemToShadow(shadow): 0x120000000000 0x123fffffffff 0x128000000000 0x13ffffffffff
    redzone=16
    max_redzone=2048
    quarantine_size_mb=256M
    malloc_context_size=30
    SHADOW_SCALE: 3
    SHADOW_GRANULARITY: 8
    SHADOW_OFFSET: 0x100000000000
    ==49393==Installed the sigaction for signal 11
    ==49393==Installed the sigaction for signal 10
    ==49393==T0: stack [0x7fff58272000,0x7fff59272000) size 0x1000000; local=0x7fff5926d130
    ==49393==AddressSanitizer Init done
    usage: doctest.py [-h] [-v]
                      [-o {DONT_ACCEPT_TRUE_FOR_1,DONT_ACCEPT_BLANKLINE,NORMALIZE_WHITESPACE,ELLIPSIS,SKIP,IGNORE_EXCEPTION_DETAIL,REPORT_UDIFF,REPORT_CDIFF,REPORT_NDIFF,REPORT_ONLY_FIRST_FAILURE,FAIL_FAST}]
                      [-f]
                      file [file ...]
    doctest.py: error: argument -o/--option: invalid choice: 'nosuchoption' (choose from 'DONT_ACCEPT_TRUE_FOR_1', 'DONT_ACCEPT_BLANKLINE', 'NORMALIZE_WHITESPACE', 'ELLIPSIS', 'SKIP', 'IGNORE_EXCEPTION_DETAIL', 'REPORT_UDIFF', 'REPORT_CDIFF', 'REPORT_NDIFF', 'REPORT_ONLY_FIRST_FAILURE', 'FAIL_FAST')
**********************************************************************
1 items had failures:
   9 of  22 in test.test_doctest.test_CLI
***Test Failed*** 9 failures.
0:00:18 load avg: 2.96 [  9/405] test_doctest2 -- test_doctest failed
0:01:59 load avg: 2.15 [ 26/405] test_asyncore -- test_asyncio failed in 58 sec
0:02:03 load avg: 2.15 [ 31/405] test_baseexception -- test_base64 failed
0:02:41 load avg: 1.63 [ 40/405] test_bufio -- test_buffer failed in 37 sec
0:04:16 load avg: 1.92 [ 46/405] test_cgi -- test_capi failed in 39 sec
0:04:20 load avg: 2.00 [ 51/405] test_cmd -- test_cmath failed
0:05:44 load avg: 1.79 [ 75/405] test_complex -- test_compileall failed
0:05:45 load avg: 1.79 [ 76/405] test_concurrent_futures -- test_complex failed
0:07:06 load avg: 1.75 [ 77/405] test_configparser -- test_concurrent_futures failed in 1 min 20 sec
0:07:19 load avg: 1.66 [ 89/405] test_datetime -- test_curses skipped (resource denied)
0:07:55 load avg: 1.83 [101/405] test_dict_version -- test_devpoll skipped
0:08:06 load avg: 1.78 [106/405] test_distutils
/var/folders/x6/9znvyjk52k1drx1h8fl0b0cc0000gn/T/tmp4m__ybpp/deptargetmodule.c:7:2: error: "Unexpected target"
#error "Unexpected target"
 ^
1 error generated.
==66997==T350: stack [0x70000b0c8000,0x70000b5c8000) size 0x500000; local=0x70000b5c7eb0
==66997==T350 TSDDtor
==66997==T350 exited
==66997==T351: stack [0x70000b0c8000,0x70000b5c8000) size 0x500000; local=0x70000b5c7eb0
/var/folders/x6/9znvyjk52k1drx1h8fl0b0cc0000gn/T/tmp6dahpgw2/deptargetmodule.c:7:2: error: "Unexpected target"
#error "Unexpected target"
 ^
1 error generated.
0:09:50 load avg: 2.30 [125/405] test_fcntl -- test_faulthandler failed in 43 sec
0:09:56 load avg: 2.20 [128/405] test_filecmp -- test_file_eintr failed
0:10:13 load avg: 2.23 [138/405] test_frame -- test_fractions failed
0:10:32 load avg: 2.33 [149/405] test_generator_stop -- test_gdb skipped
0:10:35 load avg: 2.33 [154/405] test_getopt -- test_getargs2 failed
0:12:41 load avg: 1.98 [182/405] test_ioctl -- test_io failed in 1 min 7 sec
0:13:17 load avg: 2.01 [189/405] test_keyword -- test_json failed
0:13:20 load avg: 2.17 [190/405] test_keywordonlyarg -- test_keyword failed
0:15:19 load avg: 1.97 [200/405] test_longexp -- test_long failed
0:15:53 load avg: 2.15 [208/405] test_memoryio -- test_math failed
0:16:05 load avg: 2.20 [215/405] test_modulefinder -- test_module failed
0:16:08 load avg: 2.27 [217/405] test_multibytecodec -- test_msilib skipped
0:16:18 load avg: 2.07 [219/405] test_multiprocessing_forkserver -- test_multiprocessing_fork skipped
0:16:19 load avg: 2.07 [220/405] test_multiprocessing_main_handling -- test_multiprocessing_forkserver skipped
0:16:19 load avg: 2.07 [221/405] test_multiprocessing_spawn -- test_multiprocessing_main_handling skipped
0:16:44 load avg: 1.93 [234/405] test_osx_env -- test_ossaudiodev skipped (resource denied)
dyld: Library not loaded: /usr/local/Cellar/python3/3.6.2_1/lib/libpython3.6dm.dylib
  Referenced from: /Users/dojo/Library/Caches/Homebrew/Python-3.6.2/python
  Reason: image not found
0:18:49 load avg: 1.86 [269/405] test_range -- test_random failed
0:19:02 load avg: 1.65 [272/405] test_regrtest -- test_readline failed
0:21:39 load avg: 1.57 [297/405] test_sndhdr -- test_smtpnet skipped (resource denied)
/Users/dojo/Library/Caches/Homebrew/Python-3.6.2/Lib/test/test_socket.py:2103: RuntimeWarning: received malformed or improperly-truncated ancillary data
  result = sock.recvmsg_into([buf], *args)
0:22:18 load avg: 1.77 [300/405] test_sort -- test_socketserver skipped (resource denied)
0:22:25 load avg: 1.79 [303/405] test_sqlite -- test_spwd skipped
0:22:25 load avg: 1.79 [304/405] test_ssl -- test_sqlite skipped
0:23:01 load avg: 1.87 [308/405] test_strftime -- test_statistics failed
0:22:56 load avg: 1.78 [305/405] test_startfile -- test_ssl failed in 30 sec
0:22:56 load avg: 1.78 [306/405] test_stat -- test_startfile skipped
0:23:01 load avg: 1.87 [308/405] test_strftime -- test_statistics failed
0:23:16 load avg: 1.91 [315/405] test_structmembers -- test_struct failed
0:23:18 load avg: 1.99 [319/405] test_sunau -- test_subprocess skipped
0:23:21 load avg: 1.99 [323/405] test_symtable -- test_symbol failed
0:25:01 load avg: 2.03 [339/405] test_threading_local -- test_threading failed
0:25:11 load avg: 1.94 [342/405] test_timeit -- test_time failed
0:25:12 load avg: 1.94 [344/405] test_tix -- test_timeout skipped (resource denied)
0:25:12 load avg: 1.94 [345/405] test_tk -- test_tix skipped (resource denied)
0:25:13 load avg: 1.94 [346/405] test_tokenize -- test_tk skipped (resource denied)
0:25:36 load avg: 2.05 [348/405] test_trace -- test_tools failed
0:25:59 load avg: 1.97 [350/405] test_tracemalloc -- test_traceback failed
0:26:08 load avg: 1.97 [352/405] test_ttk_textonly -- test_ttk_guionly skipped (resource denied)
0:27:48 load avg: 1.52 [371/405] test_urllib_response -- test_urllib2net skipped (resource denied)
0:27:49 load avg: 1.52 [373/405] test_urlparse -- test_urllibnet skipped (resource denied)
0:29:11 load avg: 1.32 [384/405] test_wave -- test_warnings failed
0:30:30 load avg: 2.20 [389/405] test_winreg -- test_winconsoleio skipped
0:30:31 load avg: 2.20 [390/405] test_winsound -- test_winreg skipped
0:30:31 load avg: 2.20 [391/405] test_with -- test_winsound skipped (resource denied)
0:30:32 load avg: 2.20 [392/405] test_wsgiref
0:30:46 load avg: 2.16 [399/405] test_yield_from -- test_xmlrpc_net skipped (resource denied)
*** WARNING: renaming "_sqlite3" since importing it failed: dlopen(build/lib.macosx-10.12.6-x86_64-3.6-pydebug/_sqlite3.cpython-36dm-darwin.so, 2): Symbol not found: _sqlite3_enable_load_extension
  Referenced from: /Users/dojo/Library/Caches/Homebrew/Python-3.6.2/build/lib.macosx-10.12.6-x86_64-3.6-pydebug/_sqlite3.cpython-36dm-darwin.so
  Expected in: flat namespace
 in /Users/dojo/Library/Caches/Homebrew/Python-3.6.2/build/lib.macosx-10.12.6-x86_64-3.6-pydebug/_sqlite3.cpython-36dm-darwin.so


